base: '%env(TYPO3_BASE_DOMAIN)%'
dependencies:
  - typo3-incubator/fcbigfoot-local
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: 'FC Bigfoot'
